### ISSUE TITLE
BUG: Updating User using the Client, throws an error

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Client.Web#122]
**Describe the bug**
When a user is being created, pressing "save" button, after receiving the password, throws an error.
**Note:** the user is created.

**To Reproduce**
1. Go to [test env](https://test.cherrytwist.org/admin/users/)
2. Click on "New" button
3. Scroll down to fill in the user details
4. Press "Save" button - user password is displayed
5. Press "Save" button again - error is thrown:, it always uses userId: 0, instead of taking the current userId

`{"errors":[{"message":"Unable to update user with ID: 0","locations":[{"line":2,"column":3}],"path":["updateUser"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["Error: Unable to update user with ID: 0","    at UserService.updateUser (/usr/src/app/dist/domain/user/user.service.js:190:19)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)","    at async UserResolver.updateUser (/usr/src/app/dist/domain/user/user.resolver.js:35:22)","    at async target (/usr/src/app/node_modules/@nestjs/core/helpers/external-context-creator.js:76:28)","    at async /usr/src/app/node_modules/@nestjs/core/helpers/external-proxy.js:9:24"]}}}],"data":null}`

**Expected behavior**
When saving user creation, none error must be thrown.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/2c7b6393-b76b-49ff-98b9-bf4b78d02ff6)

**Comment by Comoque1** [comment]
The issue is not reproducible anymore, hence - closing
